const baseMarketCatalogGames = [
  {
    key: 'mobile-legends',
    name: 'Mobile Legends',
    description: 'Malaysia MLBB diamonds, weekly passes, and special bundles.',
    image_url: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=900&q=80',
  },
  {
    key: 'free-fire',
    name: 'Free Fire',
    description: 'Garena Free Fire diamonds, memberships, and Evo Access packs.',
    image_url: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?auto=format&fit=crop&w=900&q=80',
  },
  {
    key: 'pubg-mobile',
    name: 'PUBG Mobile',
    description: 'PUBG Mobile UC voucher packages for Malaysia players.',
    image_url: 'https://images.unsplash.com/photo-1560253023-3ec5d502959f?auto=format&fit=crop&w=900&q=80',
  },
  {
    key: 'genshin-impact',
    name: 'Genshin Impact',
    description: 'Genesis Crystals, Chronal Nexus, and Welkin Moon top-ups.',
    image_url: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=900&q=80',
  },
  {
    key: 'magic-chess-go-go',
    name: 'Magic Chess: Go Go',
    description: 'Magic Chess passes and currency top-up options.',
    image_url: 'https://images.unsplash.com/photo-1611996575749-79a3a250f948?auto=format&fit=crop&w=900&q=80',
  },
  {
    key: 'honor-of-kings',
    name: 'Honor of Kings',
    description: 'Tokens and vouchers for Honor of Kings players.',
    image_url: 'https://images.unsplash.com/photo-1511882150382-421056c89033?auto=format&fit=crop&w=900&q=80',
  },
  {
    key: 'wuthering-waves',
    name: 'Wuthering Waves',
    description: 'Lunites and subscription packs for Wuthering Waves.',
    image_url: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=900&q=80',
  },
  {
    key: 'valorant',
    name: 'Valorant',
    description: 'Valorant Points and Riot voucher top-up options.',
    image_url: 'https://images.unsplash.com/photo-1542751110-97427bbecf20?auto=format&fit=crop&w=900&q=80',
  },
  {
    key: 'where-winds-meet',
    name: 'Where Winds Meet',
    description: 'Currency packages for Where Winds Meet.',
    image_url: 'https://images.unsplash.com/photo-1518709268805-4e9042af2176?auto=format&fit=crop&w=900&q=80',
  },
  {
    key: 'pokemon-unite',
    name: 'Pokemon Unite',
    description: 'Aeos Gems and Pokemon Unite top-up packages.',
    image_url: 'https://images.unsplash.com/photo-1605979257913-1704eb7b6246?auto=format&fit=crop&w=900&q=80',
  },
  {
    key: 'ghost-story-love-destiny',
    name: 'Ghost Story: Love Destiny',
    description: 'Premium currency packages for Ghost Story: Love Destiny.',
    image_url: 'https://images.unsplash.com/photo-1529243856184-fd5465488984?auto=format&fit=crop&w=900&q=80',
  },
  {
    key: 'mu-origin-2',
    name: 'MU Origin 2',
    description: 'Diamonds and vouchers for MU Origin 2.',
    image_url: 'https://images.unsplash.com/photo-1551103782-8ab07afd45c1?auto=format&fit=crop&w=900&q=80',
  },
  {
    key: 'racing-master',
    name: 'Racing Master',
    description: 'Voucher and currency packages for Racing Master.',
    image_url: 'https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&w=900&q=80',
  },
  {
    key: 'punishing-gray-raven',
    name: 'Punishing: Gray Raven',
    description: 'Rainbow Cards and PGR top-up options.',
    image_url: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?auto=format&fit=crop&w=900&q=80',
  },
  {
    key: 'call-of-duty-mobile-garena',
    name: 'Call of Duty Mobile (Garena)',
    description: 'CP and Garena-region Call of Duty Mobile top-ups.',
    image_url: 'https://images.unsplash.com/photo-1593305841991-05c297ba4575?auto=format&fit=crop&w=900&q=80',
  },
  {
    key: 'once-human',
    name: 'Once Human',
    description: 'Premium currency options for Once Human.',
    image_url: 'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=900&q=80',
  },
  {
    key: 'haikyu-fly-high-garena',
    name: 'Haikyu!! Fly High (Garena)',
    description: 'Garena Haikyu!! Fly High top-up packages.',
    image_url: 'https://images.unsplash.com/photo-1546519638-68e109498ffc?auto=format&fit=crop&w=900&q=80',
  },
  {
    key: 'delta-force',
    name: 'Delta Force',
    description: 'Delta Force currency and pass packages.',
    image_url: 'https://images.unsplash.com/photo-1519074069444-1ba4fff66d16?auto=format&fit=crop&w=900&q=80',
  },
  {
    key: 'dream-and-lethe-record',
    name: 'Dream and Lethe Record',
    description: 'Dream and Lethe Record recharge packages.',
    image_url: 'https://images.unsplash.com/photo-1519608487953-e999c86e7455?auto=format&fit=crop&w=900&q=80',
  },
  {
    key: 'lineage2m',
    name: 'Lineage2M',
    description: 'Lineage2M diamonds and recharge packages.',
    image_url: 'https://images.unsplash.com/photo-1508061253366-f7da158b6d46?auto=format&fit=crop&w=900&q=80',
  },
  {
    key: 'marvel-rivals',
    name: 'Marvel Rivals',
    description: 'Lattice and premium packs for Marvel Rivals.',
    image_url: 'https://images.unsplash.com/photo-1608889825103-eb5ed706fc64?auto=format&fit=crop&w=900&q=80',
  },
  {
    key: 'league-of-legends',
    name: 'League Of Legends',
    description: 'Riot Points and League of Legends voucher options.',
    image_url: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=900&q=80',
  },
  {
    key: 'tom-and-jerry-chase-global',
    name: 'Tom and Jerry: Chase (Global)',
    description: 'Global-region Tom and Jerry: Chase top-ups.',
    image_url: 'https://images.unsplash.com/photo-1605902711622-cfb43c4437d7?auto=format&fit=crop&w=900&q=80',
  },
  {
    key: 'league-of-legends-wild-rift',
    name: 'League Of Legends: Wild Rift',
    description: 'Wild Cores and Wild Rift voucher packages.',
    image_url: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=900&q=80',
  },
  {
    key: 'marvel-duel-android',
    name: 'Marvel Duel (Android)',
    description: 'Marvel Duel Android top-up packages.',
    image_url: 'https://images.unsplash.com/photo-1612036782180-6f0b6cd846fe?auto=format&fit=crop&w=900&q=80',
  },
  {
    key: 'nikke',
    name: 'Goddess of Victory: Nikke',
    description: 'Nikke gems and premium currency packages.',
    image_url: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=900&q=80',
  },
  {
    key: 'metal-slug-awakening',
    name: 'Metal Slug: Awakening',
    description: 'Metal Slug: Awakening currency and pass packs.',
    image_url: 'https://images.unsplash.com/photo-1552820728-8b83bb6b773f?auto=format&fit=crop&w=900&q=80',
  },
  {
    key: 'ragnarok-crush',
    name: 'Ragnarok Crush',
    description: 'Ragnarok Crush top-up packages.',
    image_url: 'https://images.unsplash.com/photo-1518709268805-4e9042af2176?auto=format&fit=crop&w=900&q=80',
  },
  {
    key: 'ragnarok-m-classic',
    name: 'Ragnarok M Classic',
    description: 'Ragnarok M Classic premium currency.',
    image_url: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?auto=format&fit=crop&w=900&q=80',
  },
  {
    key: 'ragnarok-m-eternal-love',
    name: 'Ragnarok M: Eternal Love',
    description: 'Ragnarok M Eternal Love top-up options.',
    image_url: 'https://images.unsplash.com/photo-1508061253366-f7da158b6d46?auto=format&fit=crop&w=900&q=80',
  },
  {
    key: 'ragnarok-x-next-generation',
    name: 'Ragnarok X Next Generation',
    description: 'ROX diamonds and top-up packages.',
    image_url: 'https://images.unsplash.com/photo-1511882150382-421056c89033?auto=format&fit=crop&w=900&q=80',
  },
  {
    key: 'ragnarok-origin-global',
    name: 'Ragnarok Origin Global',
    description: 'Ragnarok Origin Global Nyan Berry packages.',
    image_url: 'https://images.unsplash.com/photo-1529243856184-fd5465488984?auto=format&fit=crop&w=900&q=80',
  },
  {
    key: 'the-ragnarok',
    name: 'The Ragnarok',
    description: 'The Ragnarok recharge products.',
    image_url: 'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=900&q=80',
  },
  {
    key: 'revelation-infinite-journey',
    name: 'Revelation: Infinite Journey',
    description: 'Revelation: Infinite Journey currency packs.',
    image_url: 'https://images.unsplash.com/photo-1519608487953-e999c86e7455?auto=format&fit=crop&w=900&q=80',
  },
  {
    key: 'snowbreak-containment-zone',
    name: 'Snowbreak: Containment Zone',
    description: 'Snowbreak premium currency packages.',
    image_url: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=900&q=80',
  },
  {
    key: 'moonlight-blade-m',
    name: 'Moonlight Blade M',
    description: 'Moonlight Blade M top-up packages.',
    image_url: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=900&q=80',
  },
  {
    key: 'dragon-nest-m-classic',
    name: 'Dragon Nest M Classic',
    description: 'Dragon Nest M Classic top-up packages.',
    image_url: 'https://images.unsplash.com/photo-1551103782-8ab07afd45c1?auto=format&fit=crop&w=900&q=80',
  },
  {
    key: 'identity-v',
    name: 'Identity V',
    description: 'Echoes and Identity V recharge packages.',
    image_url: 'https://images.unsplash.com/photo-1608889825103-eb5ed706fc64?auto=format&fit=crop&w=900&q=80',
  },
  {
    key: 'eggy-party',
    name: 'Eggy Party',
    description: 'Eggy Coins and Eggy Party recharge options.',
    image_url: 'https://images.unsplash.com/photo-1605979257913-1704eb7b6246?auto=format&fit=crop&w=900&q=80',
  },
  {
    key: 'sausage-man',
    name: 'Sausage Man',
    description: 'Sausage Man candies and top-up packages.',
    image_url: 'https://images.unsplash.com/photo-1552820728-8b83bb6b773f?auto=format&fit=crop&w=900&q=80',
  },
  {
    key: 'football-master-2',
    name: 'Football Master 2',
    description: 'Football Master 2 recharge packages.',
    image_url: 'https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d?auto=format&fit=crop&w=900&q=80',
  },
  {
    key: 'crystal-of-atlan',
    name: 'Crystal of Atlan',
    description: 'Crystal of Atlan top-up products.',
    image_url: 'https://images.unsplash.com/photo-1518709268805-4e9042af2176?auto=format&fit=crop&w=900&q=80',
  },
  {
    key: 'arena-breakout',
    name: 'Arena Breakout',
    description: 'Bonds and Arena Breakout currency packages.',
    image_url: 'https://images.unsplash.com/photo-1519074069444-1ba4fff66d16?auto=format&fit=crop&w=900&q=80',
  },
  {
    key: 'arena-breakout-infinite',
    name: 'Arena Breakout: Infinite',
    description: 'Arena Breakout Infinite top-up products.',
    image_url: 'https://images.unsplash.com/photo-1593305841991-05c297ba4575?auto=format&fit=crop&w=900&q=80',
  },
  {
    key: 'state-of-survival',
    name: 'State of Survival',
    description: 'Biocaps and State of Survival recharge packages.',
    image_url: 'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=900&q=80',
  },
  {
    key: 'dragon-raja',
    name: 'Dragon Raja',
    description: 'Dragon Raja coupons and top-up packages.',
    image_url: 'https://images.unsplash.com/photo-1508061253366-f7da158b6d46?auto=format&fit=crop&w=900&q=80',
  },
  {
    key: 'mu-origin-3-sea',
    name: 'MU Origin 3 (SEA)',
    description: 'MU Origin 3 SEA recharge packages.',
    image_url: 'https://images.unsplash.com/photo-1519608487953-e999c86e7455?auto=format&fit=crop&w=900&q=80',
  },
  {
    key: 'be-the-king',
    name: 'Be The King: Judge Destiny',
    description: 'Gold and Be The King recharge packages.',
    image_url: 'https://images.unsplash.com/photo-1529243856184-fd5465488984?auto=format&fit=crop&w=900&q=80',
  },
  {
    key: 'age-of-empires',
    name: 'Age of Empires',
    description: 'Age of Empires mobile top-up products.',
    image_url: 'https://images.unsplash.com/photo-1518709268805-4e9042af2176?auto=format&fit=crop&w=900&q=80',
  },
  {
    key: 'life-after',
    name: 'Life After',
    description: 'Life After credits and recharge packages.',
    image_url: 'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=900&q=80',
  },
  {
    key: 'mirage-perfect-skyline',
    name: 'Mirage: Perfect Skyline',
    description: 'Mirage Perfect Skyline premium currency.',
    image_url: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=900&q=80',
  },
  {
    key: 'time-raiders',
    name: 'Time Raiders',
    description: 'Time Raiders top-up products.',
    image_url: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=900&q=80',
  },
  {
    key: 'blood-strike',
    name: 'Blood Strike',
    description: 'Gold and Blood Strike currency packs.',
    image_url: 'https://images.unsplash.com/photo-1593305841991-05c297ba4575?auto=format&fit=crop&w=900&q=80',
  },
  {
    key: 'tarisland',
    name: 'Tarisland',
    description: 'Tarisland crystal and pass packages.',
    image_url: 'https://images.unsplash.com/photo-1508061253366-f7da158b6d46?auto=format&fit=crop&w=900&q=80',
  },
  {
    key: 'king-of-avalon-global',
    name: 'King of Avalon (Global)',
    description: 'King of Avalon Global recharge packages.',
    image_url: 'https://images.unsplash.com/photo-1518709268805-4e9042af2176?auto=format&fit=crop&w=900&q=80',
  },
  {
    key: 'crisis-action',
    name: 'Crisis Action',
    description: 'Crisis Action diamonds and recharge packages.',
    image_url: 'https://images.unsplash.com/photo-1552820728-8b83bb6b773f?auto=format&fit=crop&w=900&q=80',
  },
  {
    key: 'whiteout-survival',
    name: 'Whiteout Survival',
    description: 'Frost Star and Whiteout Survival top-ups.',
    image_url: 'https://images.unsplash.com/photo-1519608487953-e999c86e7455?auto=format&fit=crop&w=900&q=80',
  },
  {
    key: 'heroes-evolved',
    name: 'Heroes Evolved',
    description: 'Heroes Evolved token packages.',
    image_url: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=900&q=80',
  },
  {
    key: 'the-legend-of-neverland-sea',
    name: 'The Legend of Neverland (SEA)',
    description: 'SEA-region The Legend of Neverland recharge products.',
    image_url: 'https://images.unsplash.com/photo-1508061253366-f7da158b6d46?auto=format&fit=crop&w=900&q=80',
  },
  {
    key: 'idle-legends-gods-saga',
    name: 'Idle Legends: GODS SAGA',
    description: 'Idle Legends GODS SAGA premium currency packages.',
    image_url: 'https://images.unsplash.com/photo-1519608487953-e999c86e7455?auto=format&fit=crop&w=900&q=80',
  },
  {
    key: 'light-of-thel-new-era',
    name: 'Light of Thel: New Era',
    description: 'Light of Thel New Era top-up packages.',
    image_url: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=900&q=80',
  },
  {
    key: 'never-after',
    name: 'Never After',
    description: 'Never After recharge and voucher packages.',
    image_url: 'https://images.unsplash.com/photo-1529243856184-fd5465488984?auto=format&fit=crop&w=900&q=80',
  },
  {
    key: 'ace-racer',
    name: 'Ace Racer',
    description: 'Ace Racer token and voucher products.',
    image_url: 'https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&w=900&q=80',
  },
  {
    key: 'super-mecha-champions',
    name: 'Super Mecha Champions',
    description: 'Super Mecha Champions premium currency top-ups.',
    image_url: 'https://images.unsplash.com/photo-1519074069444-1ba4fff66d16?auto=format&fit=crop&w=900&q=80',
  },
  {
    key: 'soul-land-new-world-voucher',
    name: 'Soul Land: New World (Voucher)',
    description: 'Soul Land New World voucher products.',
    image_url: 'https://images.unsplash.com/photo-1518709268805-4e9042af2176?auto=format&fit=crop&w=900&q=80',
  },
  {
    key: 'bleach-mobile-3d',
    name: 'Bleach Mobile 3D',
    description: 'Bleach Mobile 3D recharge packages.',
    image_url: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=900&q=80',
  },
  {
    key: 'one-punch-man-strongest-sea',
    name: 'One Punch Man: The Strongest (SEA)',
    description: 'SEA-region One Punch Man premium currency packages.',
    image_url: 'https://images.unsplash.com/photo-1608889825103-eb5ed706fc64?auto=format&fit=crop&w=900&q=80',
  },
  {
    key: 'saint-seiya-awakening-sea',
    name: 'Saint Seiya Awakening (SEA)',
    description: 'Saint Seiya Awakening SEA recharge packages.',
    image_url: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?auto=format&fit=crop&w=900&q=80',
  },
  {
    key: 'harry-potter-magic-awakened',
    name: 'Harry Potter: Magic Awakened',
    description: 'Harry Potter Magic Awakened top-up packages.',
    image_url: 'https://images.unsplash.com/photo-1518709268805-4e9042af2176?auto=format&fit=crop&w=900&q=80',
  },
  {
    key: 'silver-and-blood',
    name: 'Silver and Blood',
    description: 'Silver and Blood premium recharge products.',
    image_url: 'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=900&q=80',
  },
  {
    key: 'growtopia',
    name: 'Growtopia',
    description: 'Growtopia voucher and currency top-up options.',
    image_url: 'https://images.unsplash.com/photo-1552820728-8b83bb6b773f?auto=format&fit=crop&w=900&q=80',
  },
  {
    key: 'marvel-mystic-mayhem',
    name: 'Marvel Mystic Mayhem',
    description: 'Marvel Mystic Mayhem recharge products.',
    image_url: 'https://images.unsplash.com/photo-1612036782180-6f0b6cd846fe?auto=format&fit=crop&w=900&q=80',
  },
  {
    key: 'astra-knights-of-veda',
    name: 'Astra: Knights of Veda',
    description: 'Astra Knights of Veda premium currency packages.',
    image_url: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=900&q=80',
  },
  {
    key: 'starfall-fantasy-neverland-sea',
    name: 'Starfall Fantasy: Neverland (SEA)',
    description: 'SEA-region Starfall Fantasy recharge packages.',
    image_url: 'https://images.unsplash.com/photo-1508061253366-f7da158b6d46?auto=format&fit=crop&w=900&q=80',
  },
  {
    key: 'bleach-soul-resonance',
    name: 'Bleach: Soul Resonance',
    description: 'Bleach Soul Resonance top-up products.',
    image_url: 'https://images.unsplash.com/photo-1608889825103-eb5ed706fc64?auto=format&fit=crop&w=900&q=80',
  },
  {
    key: 'love-and-deepspace',
    name: 'Love and Deepspace',
    description: 'Love and Deepspace crystal and pass packages.',
    image_url: 'https://images.unsplash.com/photo-1519608487953-e999c86e7455?auto=format&fit=crop&w=900&q=80',
  },
  {
    key: 'kuroko-basketball-sr-sea',
    name: "Kuroko's Basketball: SR (SEA)",
    description: 'SEA-region Kuroko Basketball SR recharge packages.',
    image_url: 'https://images.unsplash.com/photo-1546519638-68e109498ffc?auto=format&fit=crop&w=900&q=80',
  },
  {
    key: 'duet-night-abyss',
    name: 'Duet Night Abyss',
    description: 'Duet Night Abyss premium currency products.',
    image_url: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=900&q=80',
  },
  {
    key: 'sword-of-justice',
    name: 'Sword of Justice',
    description: 'Sword of Justice recharge packages.',
    image_url: 'https://images.unsplash.com/photo-1518709268805-4e9042af2176?auto=format&fit=crop&w=900&q=80',
  },
  {
    key: 'rainbow-six-mobile',
    name: 'Rainbow Six Mobile',
    description: 'Rainbow Six Mobile credits and voucher products.',
    image_url: 'https://images.unsplash.com/photo-1593305841991-05c297ba4575?auto=format&fit=crop&w=900&q=80',
  },
  {
    key: 'tom-and-jerry-chase-indonesia',
    name: 'Tom and Jerry: Chase (Indonesia)',
    description: 'Indonesia-region Tom and Jerry: Chase top-ups.',
    image_url: 'https://images.unsplash.com/photo-1605902711622-cfb43c4437d7?auto=format&fit=crop&w=900&q=80',
  },
  {
    key: 'last-hunter-k-seoul',
    name: 'Last Hunter K: Seoul',
    description: 'Last Hunter K Seoul recharge packages.',
    image_url: 'https://images.unsplash.com/photo-1519074069444-1ba4fff66d16?auto=format&fit=crop&w=900&q=80',
  },
];

const providerGameCatalog = [
  ['arena-breakout', 'Arena Breakout', 12, 'Arena Breakout Bonds and currency services.'],
  ['dragon-nest-m-sea', 'Dragon Nest M : Sea', 11, 'SEA-region Dragon Nest M top-up services.'],
  ['eggy-party', 'Eggy Party', 12, 'Eggy Coins and Eggy Party recharge services.'],
  ['free-fire-instant', 'Free Fire Instant', 109, 'Instant Free Fire diamond and membership services.'],
  ['free-fire-promo', 'Free Fire Promo', 30, 'Promotional Free Fire diamond and membership services.'],
  ['garena-blood-strike', 'Garena Blood Strike', 6, 'Garena Blood Strike Gold services.'],
  ['garena-delta-force-id', 'Garena Delta Force ID', 14, 'Indonesia-region Garena Delta Force services.'],
  ['garena-free-fire-global', 'Garena Free Fire Global', 18, 'Global Free Fire diamond and membership services.'],
  ['genshin-impact', 'Genshin Impact', 55, 'Genesis Crystals, Blessing, and Genshin Impact services.'],
  ['honkai-star-rail', 'Honkai Star: Rail', 21, 'Oneiric Shards and Express Supply Pass services.'],
  ['honor-of-kings', 'Honor of Kings', 10, 'Honor of Kings token and voucher services.'],
  ['life-after-credits', 'Life After Credits', 8, 'Life After credit recharge services.'],
  ['magic-chess-go-go', 'Magic Chess: Go Go', 19, 'Magic Chess passes and currency services.'],
  ['marvel-rivals', 'Marvel Rivals', 6, 'Marvel Rivals Lattice services.'],
  ['mobile-legends-br', 'Mobile Legends BR', 18, 'Brazil-region Mobile Legends diamond services.'],
  ['mlbr', 'Mobile Legends Brazil', 23, 'Brazil-region Mobile Legends diamond services.'],
  ['mobile-legends-gift', 'Mobile Legends Gift', 2, 'Mobile Legends gift services.'],
  ['mlgb', 'Mobile Legends Global', 37, 'Global Mobile Legends diamond services.'],
  ['mlid', 'Mobile Legends ID', 36, 'Indonesia-region Mobile Legends diamond services.'],
  ['mlidpromo', 'Mobile Legends ID Promo', 39, 'Promotional Indonesia-region Mobile Legends diamond services.'],
  ['mlmy', 'Mobile Legends MY', 32, 'Malaysia-region Mobile Legends diamond services.'],
  ['mlph', 'Mobile Legends PH', 17, 'Philippines-region Mobile Legends diamond services.'],
  ['mlsg', 'Mobile Legends SG', 20, 'Singapore-region Mobile Legends diamond services.'],
  ['mlturkey', 'Mobile Legends Turkey', 10, 'Turkey-region Mobile Legends diamond services.'],
  ['mlvilog', 'Mobile Legends Via Login', 1, 'Mobile Legends via-login service.'],
  ['pbid', 'Point Blank ID', 7, 'Indonesia-region Point Blank top-up services.'],
  ['pubgg', 'PUBG Global', 6, 'Global PUBG Mobile UC services.'],
  ['pubgid', 'PUBG Indonesia', 6, 'Indonesia-region PUBG Mobile UC services.'],
  ['robuxvilog', 'Roblox Via Login', 19, 'Roblox via-login Robux services.'],
  ['token-listrik', 'Token Listrik', 4, 'Token Listrik prepaid services.'],
  ['valo', 'Valorant', 18, 'Valorant Points and voucher services.'],
  ['where-winds-meet', 'Where Winds Meet', 12, 'Where Winds Meet currency services.'],
  ['wuwa', 'Wuthering Waves', 7, 'Wuthering Waves Lunites and subscription services.'],
  ['zzz', 'Zenless Zone Zero', 7, 'Zenless Zone Zero Monochrome services.'],
].map(([key, name, services, summary]) => ({
  key,
  name,
  description: `${summary} Provider slug: ${key}. Services: ${services}.`,
  image_url: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=900&q=80',
  provider_slug: key,
  service_count: services,
}));

const marketCatalogGames = Array.from(
  new Map([...baseMarketCatalogGames, ...providerGameCatalog].map((game) => [game.key, game])).values()
);

const sources = {
  gamejusMlbb: 'https://gamejus.com/product/UID/mobile-legends-bang-bang-MY',
  gamejusFreeFire: 'https://gamejus.com/product/UID/free-fire-MY',
  lapakgamingPubg: 'https://www.lapakgaming.com/en-my/pubg-mobile',
  codashopGenshin: 'https://www.codashop.com/en-my/genshin-impact',
};

const marketCatalogProducts = [
  ['mobile-legends', '14 Diamonds', '13 + 1 Bonus', 0.96, 'GameJus', sources.gamejusMlbb],
  ['mobile-legends', '42 Diamonds', '38 + 4 Bonus', 2.89, 'GameJus', sources.gamejusMlbb],
  ['mobile-legends', '55 Diamonds', '50 + 5 Bonus', 3.78, 'GameJus', sources.gamejusMlbb],
  ['mobile-legends', 'Weekly Elite Bundle', 'Weekly Elite Bundle', 3.83],
  ['mobile-legends', 'Super Value Pass', 'Super Value Pass', 3.97],
  ['mobile-legends', '70 Diamonds', '64 + 6 Bonus', 4.85],
  ['mobile-legends', 'Weekly Pass', 'Malaysia ID', 8.04, 'GameJus', sources.gamejusMlbb],
  ['mobile-legends', '140 Diamonds', '127 + 13 Bonus', 9.7],
  ['mobile-legends', '165 Diamonds', '150 + 15 Bonus', 11.21, 'GameJus', sources.gamejusMlbb],
  ['mobile-legends', 'Monthly Epic Bundle', 'Monthly Epic Bundle', 18.86],
  ['mobile-legends', '275 Diamonds', '250 + 25 Bonus', 18.66, 'GameJus', sources.gamejusMlbb],
  ['mobile-legends', '284 Diamonds', '254 + 30 Bonus', 19.43],
  ['mobile-legends', '355 Diamonds', '317 + 38 Bonus', 24.31],
  ['mobile-legends', '429 Diamonds', '383 + 46 Bonus', 29.16],
  ['mobile-legends', '565 Diamonds', '500 + 65 Bonus', 37.99, 'GameJus', sources.gamejusMlbb],
  ['mobile-legends', 'Twilight Pass', 'Twilight Pass', 41.74],
  ['mobile-legends', '716 Diamonds', '633 + 83 Bonus', 48.6],
  ['mobile-legends', '1446 Diamonds', '1252 + 194 Bonus', 96.92],
  ['mobile-legends', '2976 Diamonds', '2501 + 475 Bonus', 192.33, 'GameJus', sources.gamejusMlbb],
  ['mobile-legends', '7502 Diamonds', '6252 + 1250 Bonus', 474.77, 'GameJus', sources.gamejusMlbb],

  ['free-fire', 'Weekly', 'Weekly Membership', 5.86, 'GameJus', sources.gamejusFreeFire],
  ['free-fire', 'Weekly Lite', 'Weekly Lite Membership', 2.49],
  ['free-fire', 'Monthly', 'Monthly Membership', 29.3, 'GameJus', sources.gamejusFreeFire],
  ['free-fire', 'Evo Access 3D', '3 Days', 2.88],
  ['free-fire', 'Evo Access 7D', '7 Days', 4.88],
  ['free-fire', 'Evo Access 30D', '30 Days', 14.83],
  ['free-fire', '25 Diamonds', '25 Diamonds', 0.89, 'GameJus', sources.gamejusFreeFire],
  ['free-fire', '50 Diamonds', '50 Diamonds', 2.05],
  ['free-fire', '100 Diamonds', '100 Diamonds', 3.41, 'GameJus', sources.gamejusFreeFire],
  ['free-fire', '200 Diamonds', '200 Diamonds', 7.35],
  ['free-fire', '300 Diamonds', '300 Diamonds', 11.19],
  ['free-fire', '310 Diamonds', '310 Diamonds', 10.36, 'GameJus', sources.gamejusFreeFire],
  ['free-fire', '520 Diamonds', '520 Diamonds', 17.31, 'GameJus', sources.gamejusFreeFire],
  ['free-fire', '830 Diamonds', '830 Diamonds', 28.21],
  ['free-fire', '930 Diamonds', '930 Diamonds', 33.47],
  ['free-fire', '1060 Diamonds', '1060 Diamonds', 34.07, 'GameJus', sources.gamejusFreeFire],
  ['free-fire', '1580 Diamonds', '1580 Diamonds', 53.09],
  ['free-fire', '2180 Diamonds', '2180 Diamonds', 68.82, 'GameJus', sources.gamejusFreeFire],
  ['free-fire', '3240 Diamonds', '3240 Diamonds', 107.56],
  ['free-fire', '5600 Diamonds', '5600 Diamonds', 170.36, 'GameJus', sources.gamejusFreeFire],
  ['free-fire', '11500 Diamonds', '11500 Diamonds', 349.05],

  ['pubg-mobile', '60 UC', '60 UC', 3.85, 'Lapakgaming', sources.lapakgamingPubg],
  ['pubg-mobile', '325 UC', '325 UC', 19.15, 'Lapakgaming', sources.lapakgamingPubg],
  ['pubg-mobile', '660 UC', '660 UC', 37.6, 'Lapakgaming', sources.lapakgamingPubg],
  ['pubg-mobile', '1800 UC', '1800 UC', 94.12, 'Lapakgaming', sources.lapakgamingPubg],
  ['pubg-mobile', '3850 UC', '3850 UC', 188.82, 'Lapakgaming', sources.lapakgamingPubg],
  ['pubg-mobile', '8100 UC', '8100 UC', 379.39, 'Lapakgaming', sources.lapakgamingPubg],

  ['genshin-impact', '60 Genesis Crystals', '60 Genesis Crystals', 3.9, 'Codashop', sources.codashopGenshin],
  ['genshin-impact', 'Blessing of the Welkin Moon', '30 Days', 19.9, 'Codashop', sources.codashopGenshin],
  ['genshin-impact', '330 Genesis Crystals', '300 + 30 Bonus', 19.9, 'Codashop', sources.codashopGenshin],
  ['genshin-impact', '1090 Genesis Crystals', '980 + 110 Bonus', 59.9, 'Codashop', sources.codashopGenshin],
  ['genshin-impact', '2240 Genesis Crystals', '1980 + 260 Bonus', 129.9, 'Codashop', sources.codashopGenshin],
  ['genshin-impact', '3880 Genesis Crystals', '3280 + 600 Bonus', 199.9, 'Codashop', sources.codashopGenshin],
  ['genshin-impact', '8080 Genesis Crystals', '6480 + 1600 Bonus', 399.9, 'Codashop', sources.codashopGenshin],
  ['genshin-impact', '60 Chronal Nexus', '60 Chronal Nexus', 3.9, 'Codashop', sources.codashopGenshin],
  ['genshin-impact', '300 Chronal Nexus', '300 Chronal Nexus', 19.9, 'Codashop', sources.codashopGenshin],
  ['genshin-impact', '980 Chronal Nexus', '980 Chronal Nexus', 59.9, 'Codashop', sources.codashopGenshin],
  ['genshin-impact', '1980 Chronal Nexus', '1980 Chronal Nexus', 129.9, 'Codashop', sources.codashopGenshin],
  ['genshin-impact', '3280 Chronal Nexus', '3280 Chronal Nexus', 199.9, 'Codashop', sources.codashopGenshin],
  ['genshin-impact', '6480 Chronal Nexus', '6480 Chronal Nexus', 399.9, 'Codashop', sources.codashopGenshin],
].map(([gameKey, name, denomination, price, source = 'Market reference', sourceUrl = '']) => ({
  gameKey,
  name,
  denomination,
  price,
  original_price: undefined,
  market_reference: {
    source,
    source_url: sourceUrl,
    observed_price: price,
    checked_at: '2026-05-26',
  },
  is_active: true,
}));

module.exports = {
  marketCatalogGames,
  marketCatalogProducts,
};
